// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as TailscaleClient from "./tailscaleclient.js";
export {
    TailscaleClient
};

export * from "./models.js";
