// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Create as $Create} from "@wailsio/runtime";

export class Pocketbase {

    /** Creates a new Pocketbase instance. */
    constructor($$source: Partial<Pocketbase> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Pocketbase instance from a string or object.
     */
    static createFrom($$source: any = {}): Pocketbase {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Pocketbase($$parsedSource as Partial<Pocketbase>);
    }
}
