// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Call as $Call, Create as $Create} from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function PocketbaseInit(): Promise<$models.Pocketbase | null> & { cancel(): void } {
    let $resultPromise = $Call.ByID(1808847468) as any;
    let $typingPromise = $resultPromise.then(($result: any) => {
        return $$createType1($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

export function PocketbaseSetup(): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(203410435) as any;
    return $resultPromise;
}

// Private type creation functions
const $$createType0 = $models.Pocketbase.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
