// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * TailscaleService manages the Tailscale client
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Call as $Call, Create as $Create} from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as tailscale$0 from "../../../tailscale.com/client/tailscale/v2/models.js";

export function GetDevices(): Promise<tailscale$0.Device[]> & { cancel(): void } {
    let $resultPromise = $Call.ByID(1515391646) as any;
    let $typingPromise = $resultPromise.then(($result: any) => {
        return $$createType1($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

export function GetUsers(): Promise<tailscale$0.User[]> & { cancel(): void } {
    let $resultPromise = $Call.ByID(3790097945) as any;
    let $typingPromise = $resultPromise.then(($result: any) => {
        return $$createType3($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

// Private type creation functions
const $$createType0 = tailscale$0.Device.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = tailscale$0.User.createFrom;
const $$createType3 = $Create.Array($$createType2);
