// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Call as $Call, Create as $Create} from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as slog$0 from "../../../log/slog/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as ipnstate$0 from "../../../tailscale.com/ipn/ipnstate/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function GetTailscalePeers(): Promise<(ipnstate$0.PeerStatus | null)[]> & { cancel(): void } {
    let $resultPromise = $Call.ByID(1965590750) as any;
    let $typingPromise = $resultPromise.then(($result: any) => {
        return $$createType2($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

export function StartService(logger: slog$0.Logger | null): Promise<$models.TailscaleClient | null> & { cancel(): void } {
    let $resultPromise = $Call.ByID(2321878382, logger) as any;
    let $typingPromise = $resultPromise.then(($result: any) => {
        return $$createType4($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

export function TailscaleStatus(): Promise<ipnstate$0.Status | null> & { cancel(): void } {
    let $resultPromise = $Call.ByID(1809784897) as any;
    let $typingPromise = $resultPromise.then(($result: any) => {
        return $$createType6($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

// Private type creation functions
const $$createType0 = ipnstate$0.PeerStatus.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = $models.TailscaleClient.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
const $$createType5 = ipnstate$0.Status.createFrom;
const $$createType6 = $Create.Nullable($$createType5);
