// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Create as $Create} from "@wailsio/runtime";

/**
 * Addr represents an IPv4 or IPv6 address (with or without a scoped
 * addressing zone), similar to [net.IP] or [net.IPAddr].
 * 
 * Unlike [net.IP] or [net.IPAddr], Addr is a comparable value
 * type (it supports == and can be a map key) and is immutable.
 * 
 * The zero Addr is not a valid IP address.
 * Addr{} is distinct from both 0.0.0.0 and ::.
 */
export type Addr = string;

/**
 * Prefix is an IP address prefix (CIDR) representing an IP network.
 * 
 * The first [Prefix.Bits]() of [Addr]() are specified. The remaining bits match any address.
 * The range of Bits() is [0,32] for IPv4 or [0,128] for IPv6.
 */
export type Prefix = string;
